CREATE TABLE IF NOT EXISTS "pending_line_identities" (
  "uid" TEXT PRIMARY KEY,
  "displayName" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
